apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-refx
  labels:
    app: refx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: refx
  template:
    metadata:
      labels:
        app: refx
    spec:
      containers:
        - name: refx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
