apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-refx
  labels:
    app: refx
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: refx
  type: {{ .Values.serviceType }}
